vim.g.base46_cache = vim.fn.stdpath "data" .. "/nvchad/base46/"
vim.g.mapleader = " "

require("configs.pack").setup(require "plugins")

if vim.fn.isdirectory(vim.g.base46_cache) == 0 then
  pcall(function()
    require("base46").load_all_highlights()
  end)
end

-- Load cached highlights generated by base46.
if vim.fn.isdirectory(vim.g.base46_cache) == 1 then
  for _, v in ipairs(vim.fn.readdir(vim.g.base46_cache)) do
    dofile(vim.g.base46_cache .. v)
  end
end

require "cmd"
require "autocmd"
require "options"
require("configs.better_escape").setup()

vim.schedule(function()
  require "mappings"
end)
